### ISSUE TITLE
In Mail 8.x, uncustomised attributions are quoted

### ISSUE THREAD

**Issue by evildmp** [robertklep/quotefixformac#38]
Since attributions are not part of the quoted material itself, they should not be quoted.

With *custom* attributions, the default is not to increase their quote level (see #23), but it can't be corrected for *uncustomised* attributions.

Applies to beta.5.

**Comment by robertklep** [comment]
Closing this, as this isn't really a QF bug but a Mail bug (which can be "fixed" by using customized attributions).
