### ISSUE TITLE
Incompatible Plug-inc Disabled 8.2 on 10.10.2

### ISSUE THREAD

**Issue by archodessa** [robertklep/quotefixformac#42]
![screen shot 2015-02-06 at 13 05 30](https://cloud.githubusercontent.com/assets/9437256/6078404/e3a21f2a-ae00-11e4-94bc-4fd6cd3e8148.png)

**Comment by robertklep** [comment]
Which version of QuoteFix are you running? It works for me on 10.10.2 with [2.6.0 beta 6](https://github.com/robertklep/quotefixformac/releases/tag/v2.6.0-beta.6).

**Comment by archodessa** [comment]
![screen shot 2015-02-06 at 14 41 21](https://cloud.githubusercontent.com/assets/9437256/6079448/43d3c4fe-ae0e-11e4-8788-8a01d8cb5b32.png)
