### ISSUE TITLE
QuoteFix plugin neither loading nor showing alert

### ISSUE THREAD

**Issue by nicwolff** [robertklep/quotefixformac#43]
I've installed the mailbundle

![screen shot 2015-04-28 at 2 31 41 pm](https://cloud.githubusercontent.com/assets/4787/7377263/4deaafea-edb3-11e4-807c-91e6f1ce92a8.png)

and enabled bundles

![screen shot 2015-04-28 at 2 30 01 pm](https://cloud.githubusercontent.com/assets/4787/7377273/5cc17792-edb3-11e4-9b33-b2b1799450fc.png)

but Mail 8.2 (2074.6) launches without QuoteFix. Any ideas? Thanks.

**Comment by robertklep** [comment]
What's the alert that you're getting?

**Comment by nicwolff** [comment]
No alert, it just doesn't load at all. Edited the subject for clarity.

**Comment by robertklep** [comment]
Does the "NoFlaggedMailbox" plug-in work? It's strange that that's showing as a folder while QF is showing as something else (can't make out the icon).

**Comment by nicwolff** [comment]
NoFlaggedMailbox may or may not be working – I don't have any Gmail IMAP accounts now to test it against – I've removed it. I also can't seem to save Mail rules changes, so something may be weird on my end – I'll update to 10.10.3 and see if I'm still having problems.

**Comment by zmwangx** [comment]
> It's strange that that's showing as a folder while QF is showing as something else (can't make out the icon).

The icon, stupid it may sound, is "Microsoft Powerpoint Bundle"... (I don't have OP's problem; just want to point this out.)

**Comment by robertklep** [comment]
@zmwangx yeah now that you mention it, I recognize it too 😀

**Comment by nicwolff** [comment]
Thanks for your time. I've tried a couple of other Mail.app plugins, and none appears to work, so I'm closing this.

E.g. installed ReplyWithHeaders:
![screen shot 2015-07-07 at 7 42 30 pm](https://cloud.githubusercontent.com/assets/4787/8559894/5300ef8a-24e0-11e5-8992-7f2c025e501f.png)

but its Mail Prefs pane doesn't appear either:
![screen shot 2015-07-07 at 7 43 34 pm](https://cloud.githubusercontent.com/assets/4787/8559906/791ba0a2-24e0-11e5-9e99-af58f9b6d1ee.png)
