### ISSUE TITLE
Does not work with Apple Mail 9.0

### ISSUE THREAD

**Issue by AntuanKhanna** [robertklep/quotefixformac#44]
QuoteFix does not appear in preferences panel. No errors.

## Environment
* Mail 9.0 (3054) 
* OS X 10.11 (15A178w)

### UUID
```
AB695A2B-4605-4A74-A99F-AF9F9C92C41B
```

**Comment by robertklep** [comment]
If you want to test to see if it works (new version of OS X will likely break stuff, though), you can add that UUID to `~/Library/Mail/Bundles/QuoteFix.mailbundle/Contents/Info.plist` (look for the `SupportedPluginCompatibilityUUIDs` key) and see if it works.

If so (I'm not yet running 10.11 anywhere), I'd be happy to add it to the list of supported Mail versions.

**Comment by AntuanKhanna** [comment]
Clarification: "not appear in preferences panel" after I rebuild it with new UUID. Without adding UUID in `step.py` (or `Info.plist`) bundle will be automatically disabled at startup.

> new version of OS X will likely break stuff

Apparently, yes.

**Comment by alvarnell** [comment]
Tried that last week.

As you predicted: “OS X will likely break stuff”.

-Al-

**Comment by robertklep** [comment]
Hopefully I'll be able to install 10.11 in a VM somewhere in the upcoming weeks so I can take a look at what's breaking the plug-in.

**Comment by ykhemka** [comment]
I have installed El Capitan OS 10.11 and Quotefix does not work. Please advise if there is any updates.

**Comment by robertklep** [comment]
@ykhemka no updates yet. I installed El Capitan in a VM yesterday, will work on getting the plugin working somewhere next week. I'll update this issue when there's news 😀

**Comment by robertklep** [comment]
First release for El Capitan: [2.7.0-alpha.1](https://github.com/robertklep/quotefixformac/releases/tag/v2.7.0-alpha.1).

I know there's still a lot not working properly, don't need to tell me about it yet ;-)

**Comment by alvarnell** [comment]
You might want to give Developer Beta 4  a try at your earliest convenience.

**Comment by robertklep** [comment]
@alvarnell I run the public beta, not the developer beta, and as of yet there isn't a new public beta available. If there's a new UUID for Mail, I'd be happy to add it and cut a new release.

**Comment by alvarnell** [comment]
Guess you’ll have to wait then, as it’s not a new UUID. I suspect there will be another Public next week.

-Al-

**Comment by robertklep** [comment]
@alvarnell so I assume that the 2.7.0 alpha doesn't work on the latest dev beta?

**Comment by robertklep** [comment]
New alpha release: https://github.com/robertklep/quotefixformac/releases/tag/v2.7.0-alpha.2

This one works in the second public beta.

**Comment by nriley** [comment]
The customized attributions are working in this version but my signature is still ending up at the top of the  message rather than below the quoted text. (I'm running the developer beta, not the public beta, but hopefully this doesn't make any difference; the Mail build is 3073).

Thanks for keeping QuoteFix up to date!

**Comment by robertklep** [comment]
@nriley your signature appearing at the top isn't being caused by this setting being enabled?

![screen shot 2015-07-31 at 09 31 47](https://cloud.githubusercontent.com/assets/1190916/9002658/07605c98-3767-11e5-88f7-82b1ce1c5cf7.png)
(_Preferences > Signatures_)

**Comment by nriley** [comment]
Thanks, I had completely forgotten that was an option.  Works now!

**Comment by AntuanKhanna** [comment]
Current version (2.7.0-alpha.2) works great with Mail app (3075). Thank you, Robert!
