### ISSUE TITLE
[ElCap] cursor moved to top of document

### ISSUE THREAD

**Issue by robertklep** [robertklep/quotefixformac#47]

**Comment by alexlevitskycom** [comment]
The same problem at me.

**Comment by alvarnell** [comment]
I am not seeing this issue with the option enabled in v2.7.0 alpha 2 the cursor appears at the top of the document in El Capitan. When I uncheck the option the cursor appears at the bottom, just before the signature.

**Comment by robertklep** [comment]
@alvarnell which option are you referring to?

**Comment by alvarnell** [comment]
In the General section, "Move cursor to top of document after QuoteFixing".

**Comment by robertklep** [comment]
@alvarnell sadly, not for me. It's always moved to the top, regardless of that option.

**Comment by joekissell** [comment]
I am seeing the same thing as @robertklep in El Capitan with 2.7.0 alpha 2. Regardless of whether "Move cursor to top of document after QuoteFixing" is checked, the insertion point always jumps to the top. I've seen this on two different Macs.

**Comment by robertklep** [comment]
Interestingly, when you right/ctrl-click a message and choose _Reply_, it works okay.

**Comment by saaby** [comment]
Just confirming this one. Cursor is not moved to the bottom of the document, when using cmd+R, but works when right/ctrl-click+Reply.

**Comment by robertklep** [comment]
[v2.7.0 beta 1](https://github.com/robertklep/quotefixformac/releases/tag/v2.7.0-beta.1) hopefully fixes this problem.

**Comment by saaby** [comment]
Confirmed. It works.

**Comment by robertklep** [comment]
Thanks for testing, @saaby :+1:

**Comment by robertklep** [comment]
Closing this issue for now. I pushed [v2.7.0 beta 2](https://github.com/robertklep/quotefixformac/releases/tag/v2.7.0-beta.1) with some cleanups related to this issue, and also a fix for #46. Feel free to reopen if there are still cursor positioning problems remaining.
