### ISSUE TITLE
Doesn't work at El Capitan 10.11

### ISSUE THREAD

**Issue by alexlevitskycom** [robertklep/quotefixformac#49]
Unfortunately doesn't work at all. 
Do you have any ideas how to fix it?

**Comment by alvarnell** [comment]
What version? You need to be using one of the pre-release versions just to get it to load and there are apparently still some minor unresolved issues, but I haven't noticed them.

**Comment by alexlevitskycom** [comment]
Works well, just problem with cursor, sure you know what I mean.

**Comment by mkjasinski** [comment]
I have installed QuoteFix-v2.7.0-alpha.2 and doesn't work, top-posting only. Any ideas?

**Comment by robertklep** [comment]
@mkjasinski can you make sure it's not related to #47 (the cursor is moved to the top of the document after quotefixing) or [this faq](https://github.com/robertklep/quotefixformac/wiki/FAQ---Frequently-Asked-Questions#why-does-my-own-signature-appear-at-the-top-of-each-reply)?

**Comment by mkjasinski** [comment]
After 2/3 Mail application restart everything works fine.

**Comment by robertklep** [comment]
Closing this issue for now, if there are specific problems, please create a new issue.

**Comment by jasonmp85** [comment]
I'm having trouble loading the plugin at all in 10.11.1. Sigh.

**Comment by houmark** [comment]
@jasonmp85 This will always be a problem and not something the plugin itself is responsible for. @robertklep is usably fast at releasing a new version that is compatible with the latest OS version — normally within a day or two of the new OS release.

If quotefix is critical for you, I would recommend waiting with running OS updates until a few days after release or after verifying a new release of Quotefix is out.

**Comment by robertklep** [comment]
[Beta 5](https://github.com/robertklep/quotefixformac/releases/tag/v2.7.0-beta.5) works on 10.11.1
