### ISSUE TITLE
Cursor positioned below quoted mail since beta3?

### ISSUE THREAD

**Issue by marcscholl** [robertklep/quotefixformac#50]
On one of my Macs, I have beta3, on another beta2 of the El Capitan pre-release. With otherwise identical settings, the one with beta3 places the cursor UNDER the quoted mail when I reply to a mail (I have customized attributions with advanced attributions for reply and forward).

Also, when forwarding, beta3 puts the cursor below the forwarded mail, after I TAB through the To: and other header fields into the mail body.

To me, looks like this has been introduced during the change from beta2 to beta3...

**Comment by alvarnell** [comment]
In Mail Preferences->QuoteFix->Quotefixing tab, do you have “Move cursor to top of document after QuoteFixing” enabled?  That’s what was broken before.

-Al-

**Comment by robertklep** [comment]
QuoteFix, by default, should position the cursor to right above your signature. If you have your signature below the quoted mail, the cursor will be positioned below the quoted mail as well.

#47 (beta3) fixed an issue with this behaviour, but it looks like it's a bit overzealous, as it seems to ignore the option that @alvarnell is mentioning. I'll take a look at it ASAP.

**Comment by marcscholl** [comment]
@alvarnell: Yes, of course, otherwise the observed behavior would also be the expected one.

@robertklep: thanks for looking into that.

**Comment by robertklep** [comment]
@marcscholl try [beta 4](https://github.com/robertklep/quotefixformac/releases/tag/v2.7.0-beta.4).

**Comment by marcscholl** [comment]
Yep! Works again as expected. Thanks a lot,
	—Marc

On Fri, Oct 16, 2015 at 13:56h, Robert Klep <notifications@github.com> wrote (with possible deletions):

**Comment by robertklep** [comment]
@marcscholl awesome, thanks for testing :grinning:
