### ISSUE TITLE
Needs update to work in Mail 9.1

### ISSUE THREAD

**Issue by ruurd** [robertklep/quotefixformac#52]
Yep. It's that thing again. I upgraded OS X to 10.11.1 and consequently Mail has been upgraded to 9.1 and - surprise - the quotefix plugin is rejected as incompatible.

Can I be of service perhaps?

**Comment by ruurd** [comment]
Oh I see you're working on it...

**Comment by robertklep** [comment]
I released 2.7.0 earlier today that works on 10.11.1 (at least for me it does 😉)

— robert

**Comment by ruurd** [comment]
Yep. I need to learn and keep my big fat mouth shut until I look further than the tip of my nose. My bad. I'll install and see what happens.

**Comment by ruurd** [comment]
Looks good. I'll close this one.

**Comment by robertklep** [comment]
👍

— robert
