### ISSUE TITLE
v2.7.0 stopped working after El Capitan update to 10.11.2

### ISSUE THREAD

**Issue by MikeMaxNow** [robertklep/quotefixformac#56]
Quotefix 2.7.0 is not compatible with El Capitan 10.11.2

How can this be fixed?

Thank you!

Mike

**Comment by alvarnell** [comment]
Have you tried v2.7.1 posted on Dec 3?

If not you can fix it with MailPluginFix
http://code2k.net/products/mailpluginfix/.

For Robert:
Results of defaults read /Applications/Mail.app/Contents/Info PluginCompatibilityUUID
1550C683-EA48-4036-B7CE-FB6F5D13EE02

**Comment by alvarnell** [comment]
Something I should have documented earlier about v2.7.0 is that Sparkle doesn't work to update to v2.7.1.

**Comment by MikeMaxNow** [comment]
Yes 2.7.1 does not fix it, but MailPluginFix does, thank you very much!

**Comment by robertklep** [comment]
Just pushed [v2.7.2](https://github.com/robertklep/quotefixformac/releases/tag/v2.7.2) which supports 10.11.2.
