### ISSUE TITLE
Support for 10.11.4

### ISSUE THREAD

**Issue by toszcze** [robertklep/quotefixformac#63]
The plugin doesn't work with Mail 9.3 (3124) in OS X 10.11.4.

**Comment by robertklep** [comment]
For the time being, you can try [this](https://github.com/robertklep/quotefixformac/wiki/FAQ---Frequently-Asked-Questions#every-time-mac-os-x-updates-i-get-a-message-that-quotefix-is-disabled) if you want.

I'll be updating my Mac soon so after that I'll take a closer look :-)

**Comment by toszcze** [comment]
Thanks. :)

**Comment by robertklep** [comment]
Are you running [2.7.4](https://github.com/robertklep/quotefixformac/releases/tag/v2.7.4)? It should support Mail 9.3

**Comment by alvarnell** [comment]
The PluginCompatibilityUUID you need for Mail 9.3 is:

71562B89-0D90-4588-8E94-A75B701D6443

-Al-

**Comment by toszcze** [comment]
@robertklep Yes, I'm running 2.7.4, but the PluginCompatibilityUUID is now different (as @alvarnell said). Anyway, adding it to Info.plist obviously worked.

**Comment by robertklep** [comment]
@toszcze I added that UUID a few weeks ago for the 2.7.4 release ([here](https://github.com/robertklep/quotefixformac/commit/1d7f85e7110c05d8379de32a3747db409358b657#diff-2eeaed663bd0d25b7e608891384b7298R122)), so not sure why it's not working.

**Comment by toszcze** [comment]
@robertklep Yes, I just noticed that for some reason I was still using 2.7.3. Sorry for that and thanks for your help. :)

**Comment by robertklep** [comment]
@toszcze no problem :-)
