### ISSUE TITLE
Mac OS 10.12 compatible QuoteFix version

### ISSUE THREAD

**Issue by Hanineal** [robertklep/quotefixformac#72]
Are you working on a 10.12 (Sierra) compatible version? If so, when will it be available?

I f you need testers, let me know.

Dan Neal

**Comment by robertklep** [comment]
Check out  [v2.8.0-alpha.1](https://github.com/robertklep/quotefixformac/releases/tag/v2.8.0-alpha.1), which should work (mostly) on Sierra.

I'll update the README to include a link to it :)

**Comment by ykhemka** [comment]
Hello,

A new version GM was released on 08.09.2016. Is there an update as Alpha-1 is not working.

**Comment by robertklep** [comment]
@ykhemka I'm installing the GM as we speak, so hopefully I'll be able to push an update later today.

**Comment by alvarnell** [comment]
The GM won’t be released until Sep 20, so what you have is just a GM candidate.

-Al-

**Comment by ykhemka** [comment]
Thank you very much.

**Comment by robertklep** [comment]
Okay, so I'm running the GM _candidate_ (😉) now, and QF (alpha-1) seems to be running just fine. Mail version is 10.0 (3226).

@ykhemka are you getting errors? Does QF load at all? Can you post the result of this Terminal command:

    defaults read /Applications/Mail.app/Contents/Info PluginCompatibilityUUID

**Comment by ykhemka** [comment]
[image: Inline image 1]

Please check as I downloaded again and installed and the error above.

**Comment by robertklep** [comment]
@ykhemka the inline image doesn't seem to work 🙁

**Comment by ykhemka** [comment]
Attached again.

**Comment by ykhemka** [comment]
<img width="187" alt="screen shot 2016-09-09 at 1 41 08 pm" src="https://cloud.githubusercontent.com/assets/8979532/18380488/34ea2d60-7695-11e6-9d93-fcdf346acda6.png">

**Comment by robertklep** [comment]
@ykhemka nope, no luck. Feel free to e-mail me directly: robert DOT klep AT gmail DOT com

**Comment by robertklep** [comment]
@ykhemka thanks for the image. It looks like you just disabled QuoteFix. You can re-enable it in the preferences.

**Comment by ykhemka** [comment]
Voila, thanks. It works now :-)

**Comment by ykhemka** [comment]
Hi,

Can you also prepare on the lines of Herald for Mac.

http://erikhinterbichler.com/apps/herald/

And

http://dervishsoftware.com

**Comment by robertklep** [comment]
When running multiple plugins, a plugin developer cannot enforce the order in which the plugins are run, so it's really difficult to act on the output of other plugins.

**Comment by ykhemka** [comment]
Oh, I understand.
