### ISSUE TITLE
Quotefix Mac OS Sierra 10.12.1 beta

### ISSUE THREAD

**Issue by ykhemka** [robertklep/quotefixformac#73]
Hello,

Please check as the current alpha version is not compatible with macOS Sierra 10.12.1 - Mail 10.1. Please advise for any updates.

Thanks,
Yash Khemka

**Comment by alvarnell** [comment]
MailPluginFix 1.3.0 <https://code2k.net/products/mailpluginfix/> should take care of that for you.

-Al-

**Comment by ykhemka** [comment]
Hi,

Thanks, even after that the following image shows, pls check attachment.

**Comment by robertklep** [comment]
I'm not running that beta yet, and I'm on a slow connection this weekend, but I'll take a look on Monday.

**Comment by ykhemka** [comment]
Thank you very much.

Best regards,
Yash Khemka

Sent from my iPhone

On 24-Sep-2016, at 11:31 AM, Robert Klep <notifications@github.com> wrote:

I'm not running that beta yet, and I'm on a slow connection this weekend, but I'll take a look on Monday.

**Comment by robertklep** [comment]
@ykhemka I just pushed [v2.8.0-alpha.2](https://github.com/robertklep/quotefixformac/releases/tag/v2.8.0-alpha.2), with support for Mail 10.1 (Sierra 10.12.1 beta).

**Comment by ykhemka** [comment]
Hi,

Thank you very much.

**Comment by ykhemka** [comment]
Hello,

The Quotefix for Mac has been disabled for Mac OS 10.12.2 Beta. I have been
using v2.8.0-alpha.2
<https://github.com/robertklep/quotefixformac/releases/tag/v2.8.0-alpha.2>:
Sierra 10.12.1 (beta) support.

Please advise and update.

Regards,
Yash Khemka

**Comment by robertklep** [comment]
@ykhemka just pushed [2.8.0-alpha.3](https://github.com/robertklep/quotefixformac/releases/tag/v2.8.0-alpha.3) with support for 10.12.2 beta.

**Comment by ykhemka** [comment]
Hi,

Thank you very much.

Yash Khemka
