### ISSUE TITLE
Sierra 10.2.2, and Mail 10.2, once again broke QuoteFix

### ISSUE THREAD

**Issue by skepticus** [robertklep/quotefixformac#74]
What the subject says.....
"Mail has disabled the following plug-ins:

	QuoteFix

Contact the makers of these plug-ins for versions that are compatible with Mail 10.2.

**Comment by robertklep** [comment]
For the time being, you could try to run [MailPluginFix](http://code2k.net/products/mailpluginfix/). Once I've updated to 10.2 I'll take a closer look.

**Comment by skepticus** [comment]
> On 12 14, 2016, at 07:16, Robert Klep <notifications@github.com> wrote:
> 
> For the time being, you could try to run MailPluginFix. Once I've updated to 10.2 I'll take a closer look.

That did seem to repair it, but I had to put the plugin into my user Library. That app does not see bundles in the system Library. (I prefer to have things available for all users….)

So, yes, thanks.

- Wade

**Comment by robertklep** [comment]
@skepticus you should be able to move the fixed plugin back to `/System/Library` (or `/Library`, not sure where the global plugin dir is located).

**Comment by robertklep** [comment]
@skepticus updated to 10.12.2 myself, but from what I can see, Mail hasn't changed since the        latest beta; [`v2.8.0-alpha.3`](https://github.com/robertklep/quotefixformac/releases/tag/v2.8.0-alpha.3) works okay for me.

If that version doesn't work for you, can you post the output of the following Terminal command:
```
defaults read /Applications/Mail.app/Contents/Info PluginCompatibilityUUID
```

Sometimes, different hardware gets different Mail versions.

**Comment by mgguinne** [comment]
Hi Robert, same issue for me. Output of command you requested.

**Comment by mgguinne** [comment]
1CD3B36A-0E3B-4A26-8F7E-5BDF96AAC97E

**Comment by mgguinne** [comment]
Thanks v2.8.0-alpha.3 fixed my issue, cheers

**Comment by skepticus** [comment]
I was able to get the bundle to work in the main /Library/Mail/Bundles, rather than my user ~/Library, but as of a week ago (last security update?) I'm getting this- 

"The QuoteFix plug-in caught an exception:

Traceback (most recent call last):
  File "/Library/Mail/Bundles/QuoteFix.mailbundle/Contents/Resources/lib/python2.7/quotefix/fixer.py", line 110, in fix
  File "/Library/Mail/Bundles/QuoteFix.mailbundle/Contents/Resources/lib/python2.7/quotefix/fixer.py", line 166, in remove_attachment_placeholders
TypeError: 'NoneType' object is not iterable

Please contact the developer quoting the contents of this alert."

'Iterable' is a new word to me. ;-)

**Comment by robertklep** [comment]
@skepticus I moved this [to a new issue](https://github.com/robertklep/quotefixformac/issues/77). As a quick fix, you can disable the _"Remove attachment placeholders"_ option.
