### ISSUE TITLE
Check validity of `_originalMessages`

### ISSUE THREAD

**Issue by robertklep** [robertklep/quotefixformac#77]
As per [this comment](https://github.com/robertklep/quotefixformac/issues/74#issuecomment-275091636):

> I was able to get the bundle to work in the main /Library/Mail/Bundles, rather than my user ~/Library, but as of a week ago (last security update?) I'm getting this-
> 
> "The QuoteFix plug-in caught an exception:
> 
> Traceback (most recent call last):
> File "/Library/Mail/Bundles/QuoteFix.mailbundle/Contents/Resources/lib/python2.7/quotefix/fixer.py", line 110, in fix
> File "/Library/Mail/Bundles/QuoteFix.mailbundle/Contents/Resources/lib/python2.7/quotefix/fixer.py", line 166, in remove_attachment_placeholders
> TypeError: 'NoneType' object is not iterable
> 
> Please contact the developer quoting the contents of this alert."
> 
> 'Iterable' is a new word to me. ;-)

**Comment by robertklep** [comment]
@skepticus try [v2.8.0-alpha.5](https://github.com/robertklep/quotefixformac/releases/tag/v2.8.0-alpha.5), which hopefully fixes the issue you ran in to.

**Comment by skepticus** [comment]
Success. Thanks so much.
