### ISSUE TITLE
Alpha 6 not working on 10.12.5 (16F73), Mail Version 10.3 (3273)

### ISSUE THREAD

**Issue by tizatron** [robertklep/quotefixformac#80]
A great plugin, been using it for years.

New laptop, and trying to get the plugin to fly.

Tried the Plugin Fix and pInfo mods per the FAQ, no joy.  But I will keep reading.

I looked in the system log and this is the only thing that I could see.

`Jun 26 10:28:20 XXXXXX-XXXXXX com.apple.xpc.launchd[1] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for integer: _DirtyJetsamMemoryLimit
Jun 26 10:28:30 --- last message repeated 1 time ---
Jun 26 10:28:30 XXXXXX-XXXXXX Mail[8172]: BUG in libdispatch client: kevent[EVFILT_MACHPORT] monitored resource vanished before the source cancel handler was invoked
Jun 26 10:30:20 XXXXXX-XXXXXX com.apple.xpc.launchd[1] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for integer: _DirtyJetsamMemoryLimit
Jun 26 10:30:21 --- last message repeated 2 times ---`

Doesn't seem that helpful - wish there was more there.

To install

Created ~/Library/Mail/Bundles
cd ~/Library/Mail/Bundles
unzip ~/Downloads/QuoteFix-v2.8.0-alpha.6.zip

Restarted Mail, cannot see the Icon in Preferences.

**Comment by robertklep** [comment]
It should work on 10.12.5.

Did you also enable plug-in support for Mail? Documented here: https://github.com/robertklep/quotefixformac#installation (first step)

**Comment by tizatron** [comment]
Thanks for getting back to me:

I ran these requests as me:

```
defaults write com.apple.mail EnableBundles -bool true
defaults write com.apple.mail BundleCompatibilityVersion -string 3
```

I got your reply and realized that on the new machine I am not admin (or root)

```
sudo bash
defaults write com.apple.mail EnableBundles -bool true
defaults write com.apple.mail BundleCompatibilityVersion -string 3
```

Plugin now shows up.

Bottom posting in back!  Sanity restored.

Sent a tiny pull request.  Might help.  Thanks for the quick reply and a good plugin.

#81

**Comment by tizatron** [comment]
Going to close this issue since running the command as root did the trick,

**Comment by robertklep** [comment]
That's unexpected, as those settings should end up in your local (user) ~/Library/ (otherwise, you'd use `defaults write -g ...`, for which you probably _do_ require root privs). I'm pretty sure that I never used `sudo` to get it working.

I'll look into it a bit more before accepting your PR :)

**Comment by tizatron** [comment]
yes - that does make more sense and the plugin should be installable without root creds - good point.
