### ISSUE TITLE
unanchored signature delimiter

### ISSUE THREAD

**Issue by jklundell** [robertklep/quotefixformac#84]
The default delimiter doesn't have a beginning-of-line anchor, so it treats any line ending with a double hyphen or dash as a delimiter. The obvious fix of adding ^ seems to work (n=1).

**Comment by robertklep** [comment]
Because of how Mail structures e-mails, using an anchor doesn't always work, which is why I chose not to use one by default.

You can set a custom regular expression in the _"Advanced"_ preferences.

**Comment by jklundell** [comment]
I have done so, finding the cure worse than the disease. Thanks.
