### ISSUE TITLE
Compatibility with Version 11.0 (3445.1.7)

### ISSUE THREAD

**Issue by Cyberek** [robertklep/quotefixformac#85]
Hi.

I have tried to manually add new Mail UUID to Plist.info, but it seems it doesn't allow to enable QuoteFix to work:
`<string>C86CD990-4660-4E36-8CDA-7454DEB2E199</string>`
I got the UUID by executing:
`defaults read /Applications/Mail.app/Contents/Info PluginCompatibilityUUID`

Anybody have an idea how to make quote fix work with latest High Sierra MacOS?

**Comment by robertklep** [comment]
Are you using the [2.9.0-alpha.1](https://github.com/robertklep/quotefixformac/releases/tag/v2.9.0-alpha.1)? That version includes that particular UUID ([here](https://github.com/robertklep/quotefixformac/blob/high-sierra-support/setup.py#L118-L121)).

**Comment by Cyberek** [comment]
Thanks @robertklep - now I see my problem, I didn't know, that there is 2.9 release (its under 2.8.2 and 2.8.1 versions in "releases" section).

**Comment by robertklep** [comment]
That's partly my fault, I should probably release a proper 2.9.0 :)
