### ISSUE TITLE
10.14.4

### ISSUE THREAD

**Issue by reekes** [robertklep/quotefixformac#93]
After the MacOS 10.14.4 update, Apple Mail 12.4 has tagged the plugin as incompatible.

**Comment by jklundell** [comment]
Curious. Works for me™. (I did have to reenable it in preferences.)

**Comment by reekes** [comment]
D'oh! I'm an idiot. I clicked on the wrong checkbox and got an error message for a different plugin.

"Never mind." - Emily Litella

**Comment by reekes** [comment]
user error, works as expected
