### ISSUE TITLE
macOS Mojave Security Update 2021-002 Kills QuoteFix

### ISSUE THREAD

**Issue by jlkane** [robertklep/quotefixformac#98]
I was happily running QuoteFix on Mojave until today, when I installed macOS Mojave Security Update 2021-002 and Safari 14.0.3.  I went through the usual song-and-dance routine of adding the UUID string to the Info.plist, but... no joy.

Any further recommendation? ...or did this security update really, truly, sincerely kill QuoteFix?

Sadly,
Jim

**Comment by robertklep** [comment]
Take a look at your device log using the Console app. When Mail starts, info may get logged on why QF isn't being loaded.

Did you (re-)enable the plugin from Mail's preferences?

**Comment by jlkane** [comment]
Holy cow, I AM an idiot!  I got the harder parts right and blew the easy step -- re-enabling the plugin!  I am SO sorry for consuming your limited bandwidth with this conversation, but I'm grateful for your support and your continued support of this much-valued plugin!

All the best,
Jim

**Comment by robertklep** [comment]
No worries, easy mistake to make! 😅 You'd think that Mail would remember that you had QF enabled to begin with (for me, it regularly disables QF for no apparent reason whatsoever…)
